### PR TITLE
Fix autoupdater

### LINKED ISSUE #12: Autoupdate keeps adding duplicated GNOME 44.1 entries every week
Just looks at [the commit history](https://github.com/brunodrugowick/notification-position-gnome-extension/commits/master), [`CHANGELOG.md`](https://github.com/brunodrugowick/notification-position-gnome-extension/blob/master/CHANGELOG.md) or [`metadata.json`](https://github.com/brunodrugowick/notification-position-gnome-extension/blob/master/src/metadata.json)

Ping @brunodrugowick

### PR DESCRIPTION
**Pull request by brunodrugowick**
Fixes #12

### CODE REVIEW

File: scripts/auto-update-from-gnome-release.sh [hunk 1]
```diff
@@ -9,7 +9,8 @@ add_gnome_support() {
 		> src/metadata.json.tmp # it fails if I write directly to the same file
 	mv src/metadata.json.tmp src/metadata.json
 
-	sed -i '7 i ## [Autoupdate]\n### Added\n- Automatically added support to new Gnome version\n\n' CHANGELOG.md
+        sed -i "7 i ## [Autoupdate]\n### Added\n- Automatically added support to new Gnome ${1} version\n" CHANGELOG.md
+        echo $1 > CURRENT_SUPPORTED_GNOME_VERSION
```
Comment (brunodrugowick) [inline scripts/auto-update-from-gnome-release.sh:13]: This is what was missing and fixes the continuous upgrade to the same version.
